---
global:
  owner: quickstart-eng@amazon.com
  qsname: quickstart-ec2-ipsec-mesh
  regions:
    - us-east-1
  reporting: true
tests:
  ipsec-test:
    parameter_input: ipsec-params.json
    regions:
      - us-east-1
    template_file: ipsec-setup.yaml